name: 'on_artifact'
description: 'Optimized for workflow_run. Download artifact and set as output then clear it'
author: 'marocchino'
inputs:
  GITHUB_TOKEN:
    description: 'set secrets.GITHUB_TOKEN here.'
    required: true
  name:
    description: 'artifact name.'
    required: true
  path:
    description: 'path to unzip it. default is artifact name.'
    required: false
  run_id:
    description: 'set github.event.workflow_run.id here.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
